### ISSUE TITLE
Código de DEFINE

### ISSUE THREAD

**Issue by Inugami** [iarroyof/define-semantic-annotation#3]
Hola.

Revise el repositorio y no veo el código fuente de DEFINE, solo el empaquetado .w2p

Puedo descargar ese paquete y trabajarlo localmente pero si se han hecho cambios desde ese commit entonces se perderan (El proposito de el repositorio es evitar esos problemas). 

También puedo subir el código con mis modificaciones pero será necesario que todos los cambios que se hicieron desde el último commit se vuelvan a agregar. (Para ello tienen que clonar el repositorio y modificar los archivos).

¿Qué hago? Si no hay cambios significativos desde el último commit entonces es mejor que yo suba el código. 

Espero respuesta.

**Comment by DMMenOrt** [comment]
en ese caso seria mejor que subieras el codigo con tus modificaciones y
nosotros volvemos a ponerle diseño y traduccion
